# Generated by Django 2.2.2 on 2019-06-20 06:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('newhome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.UUIDField(default=uuid.uuid4, help_text='generated unique id for user', primary_key=True, serialize=False, verbose_name='User Id')),
                ('u_name', models.CharField(help_text='User Name', max_length=100, null=True)),
                ('borrow_date', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('book_name', models.ForeignKey(help_text='Book Name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='newhome.Book')),
            ],
        ),
    ]
