# Generated by Django 2.2.2 on 2019-06-20 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('newhome', '0005_auto_20190620_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='return_date',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='generated unique id for customer', primary_key=True, serialize=False, verbose_name='student Id'),
        ),
    ]
