# Generated by Django 2.2.2 on 2019-06-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newhome', '0007_auto_20190620_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_branch',
            field=models.CharField(help_text='Student branch', max_length=100, null=True),
        ),
    ]
